version: '3'

services:
  web:
    container_name: beautiful_places
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - '.:/var/www/html'
    depends_on:
      - db
    links:
      - db
  db:
    container_name: bp_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: beautiful_places
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./assets/sql:/docker-entrypoint-initdb.d
